<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHpeg9in\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHpeg9in/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHpeg9in.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHpeg9in\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHpeg9in\appDevDebugProjectContainer([
    'container.build_hash' => 'Hpeg9in',
    'container.build_id' => '0a45195a',
    'container.build_time' => 1573156171,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHpeg9in');
